version: "3.8"
name: 'booking-meeting-rooms'

services:
  pgdb:
    image: postgres:15.6-alpine3.19
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
